refactor: add the marks with exit codes to error messages

diff --git a/bin/polyglot b/bin/polyglot
--- a/bin/polyglot
+++ b/bin/polyglot
@@ -47,6 +47,13 @@ api_url=${API_URL:-$api_url}
 
 support_url='https://github.com/clickcaramel/PolyglotRocks#support'
 support_email='support@polyglot.rocks'
+exit_code_mark='POLYGLOT_EXIT_CODE'
+
+translation_error_code=50
+translation_error_mark="$exit_code_mark: $translation_error_code"
+
+free_plan_exhausted_code=42
+free_plan_exhausted_mark="$exit_code_mark: $free_plan_exhausted_code"
 
 product_id=$PRODUCT_BUNDLE_IDENTIFIER
 base_language='en'
@@ -318,10 +325,12 @@ translate_string() {
         echo "You've reached limits of your free plan. Subscribe to remove the limits"
         echo "Premium plan with translations by humans: [$premium_url]"
         echo "Unlimited AI plan: [$unlimited_ai_url]"
+        echo "$free_plan_exhausted_mark"
     else
         echo "Something went wrong. Please try to restart Polyglot or contact our support team at $support_email. Please, provide the following information:"
         echo "Parameters: key=$id; encoded_id=$encoded_id; value=$value; descr=$descr"
         echo "Server Response: ${api_response}"
+        echo "$translation_error_mark"
     fi
 }
 
@@ -646,12 +655,12 @@ main() {
                     sleep $i
                     localisation="`translate_string \"$id\" \"$base_value\" \"$description\" \"$desired_max_length\"`"
 
-                    if [ "`echo \"$localisation\" | grep \"$api_url\"`" ]; then
+                    if [ "`echo \"$localisation\" | grep \"$free_plan_exhausted_mark\"`" ]; then
                         echo "$localisation"
-                        exit 42
+                        exit $free_plan_exhausted_code
                     fi
 
-                    if [ "`echo \"$localisation\" | grep \"$support_email\"`" ]; then
+                    if [ "`echo \"$localisation\" | grep \"$translation_error_mark\"`" ]; then
                         error_message="$localisation"
                         localisation=''
                         error "Failed to get auto-translations. Retrying for \"$id\""
@@ -662,7 +671,7 @@ main() {
 
                 if [ -z "$localisation" ]; then
                     error "Failed to get auto-translations. $error_message"
-                    exit 50
+                    exit $translation_error_code
                 fi
 
                 fill_translations_map 'auto' "$localisation"
@@ -672,7 +681,7 @@ main() {
 
                 if [ -z "$auto_translation" ]; then
                     error 'Failed to get auto-translations. Something went wrong, try to restart Polyglot'
-                    exit 50
+                    exit $translation_error_code
                 fi
             fi
 
